### PR TITLE
Bring Python to 3.9 in Travis

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by gliptak** [comment]
@billford @mcm please review

**Comment by mcm** [comment]
Hey @gliptak - I'm not sure how I feel about changing this to Python 3.9. What's the reasoning for the change? Maybe we could consider doing both?

**Comment by gliptak** [comment]
@mcm updated

**Comment by mcm** [comment]
Unfortunately, it looks like Travis-CI doesn't support 3.9 yet. You can set it to 3.9-dev which will work for now, until they release 3.9.

```
Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/16.04/x86_64/python-3.9.tar.bz2

$ curl -sSf --retry 5 -o python-3.9.tar.bz2 ${archive_url}

curl: (22) The requested URL returned error: 404 Not Found

Unable to download 3.9 archive. The archive may not exist. Please consider a different version.
```

**Comment by mcm** [comment]
Looks good. Thanks for working this out with us.

**Pull request merged**
